# Generated by Django 2.2.3 on 2020-03-19 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(blank=True, upload_to='post_images')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('location', models.CharField(max_length=32)),
                ('bio', models.CharField(max_length=256)),
                ('available', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Profession')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=32)),
                ('link', models.URLField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Profession')),
            ],
            options={
                'unique_together': {('name', 'profession')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PostTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Posts')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Tags')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.Profession'),
        ),
        migrations.AddField(
            model_name='posts',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Section'),
        ),
    ]
