# Generated by Django 2.2.3 on 2020-03-18 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='link1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='link2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='link3',
        ),
        migrations.CreateModel(
            name='UserLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=32)),
                ('link', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.UserProfile')),
            ],
        ),
    ]
