# Generated by Django 2.2.3 on 2020-03-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20200324_2024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagChecker',
        ),
    ]
