# Generated by Django 2.2.3 on 2020-03-18 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20200318_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlinks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
