# Generated by Django 2.2.3 on 2020-03-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20200318_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttags',
            old_name='pid',
            new_name='post',
        ),
    ]
