# Generated by Django 2.2.3 on 2020-03-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20200318_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlinks',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
