# Generated by Django 2.2.3 on 2020-03-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_delete_tagchecker'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='picture',
            field=models.ImageField(default='designbig.jpg', upload_to='profession_images'),
        ),
    ]
