# Generated by Django 2.2.3 on 2020-03-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20200318_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='descriptiuon',
            new_name='description',
        ),
    ]
